#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use yii\console\Application;
use yii\helpers\ArrayHelper;

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

$appDir = __DIR__;

require $appDir . '/vendor/autoload.php';
require $appDir . '/vendor/yiisoft/yii2/Yii.php';
require $appDir . '/config/bootstrap.php';

$config = ArrayHelper::merge(
    require $appDir . '/config/common.php',
    require $appDir . '/config/console.php'
);

$application = new Application($config);
$exitCode = $application->run();
exit($exitCode);
